
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package plctopascal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Twhile = 34;
  public static final int Tfloat = 14;
  public static final int Tpor = 19;
  public static final int Treturn = 16;
  public static final int Teq = 22;
  public static final int Tigualdad = 26;
  public static final int Tasig = 37;
  public static final int Tint = 13;
  public static final int Tcoma = 12;
  public static final int Tfor = 36;
  public static final int Tvoid = 9;
  public static final int Tand = 25;
  public static final int Telse = 31;
  public static final int Tdiv = 20;
  public static final int Tmayori = 29;
  public static final int Tconstint = 3;
  public static final int Tdo = 33;
  public static final int EOF = 0;
  public static final int Tparc = 8;
  public static final int Tpara = 7;
  public static final int error = 1;
  public static final int Tcorc = 11;
  public static final int Tcora = 10;
  public static final int Tmod = 21;
  public static final int Tuntil = 35;
  public static final int Tneg = 23;
  public static final int Tconstlit = 5;
  public static final int Tmenos = 18;
  public static final int Tmenor = 27;
  public static final int Tmenori = 30;
  public static final int Tor = 24;
  public static final int Tident = 2;
  public static final int Tpcoma = 15;
  public static final int Tmayor = 28;
  public static final int Tif = 32;
  public static final int Tdefine = 6;
  public static final int Tconstfloat = 4;
  public static final int Tmas = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tident",
  "Tconstint",
  "Tconstfloat",
  "Tconstlit",
  "Tdefine",
  "Tpara",
  "Tparc",
  "Tvoid",
  "Tcora",
  "Tcorc",
  "Tcoma",
  "Tint",
  "Tfloat",
  "Tpcoma",
  "Treturn",
  "Tmas",
  "Tmenos",
  "Tpor",
  "Tdiv",
  "Tmod",
  "Teq",
  "Tneg",
  "Tor",
  "Tand",
  "Tigualdad",
  "Tmenor",
  "Tmayor",
  "Tmayori",
  "Tmenori",
  "Telse",
  "Tif",
  "Tdo",
  "Twhile",
  "Tuntil",
  "Tfor",
  "Tasig"
  };
}

