/* The following code was generated by JFlex 1.6.1 */

package traductorpascalc;
import java.io.*;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/Users/Carlos Gil Sabrido/Documents/GitHub/PL2029/TraductorPascalC/src/traductorpascalc/lexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\62\1\60\1\64\1\64\1\60\22\0\1\63\6\0\1\56"+
    "\1\20\1\21\1\26\1\24\1\17\1\25\1\13\1\0\12\54\1\14"+
    "\1\15\1\22\1\16\1\23\2\0\1\44\3\52\1\41\1\52\1\42"+
    "\1\52\1\11\2\52\1\45\1\52\1\10\3\52\1\43\1\52\1\12"+
    "\1\7\5\52\2\0\1\55\1\0\1\53\1\0\1\5\1\51\1\32"+
    "\1\27\1\33\1\35\1\4\1\46\1\30\2\52\1\47\1\6\1\36"+
    "\1\3\1\1\1\52\1\2\1\40\1\37\1\34\1\31\1\50\3\52"+
    "\1\57\1\0\1\61\7\0\1\64\u1fa2\0\1\64\1\64\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\10\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\14\2"+
    "\1\17\2\1\1\20\1\21\2\2\1\22\4\2\1\23"+
    "\1\0\1\24\1\25\1\26\1\2\1\27\10\2\1\30"+
    "\4\2\5\0\2\2\1\31\1\32\2\2\1\0\1\2"+
    "\1\33\1\34\1\2\1\35\2\2\1\36\1\2\1\37"+
    "\4\2\1\40\1\0\1\40\1\41\3\2\1\42\1\2"+
    "\1\21\1\0\2\2\1\43\2\2\1\44\1\45\2\2"+
    "\1\0\5\2\1\46\1\47\1\2\1\50\1\51\2\2"+
    "\1\52\1\2\1\53\1\2\1\54\1\2\1\55\2\2"+
    "\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\65\0\u0212\0\65\0\65\0\65\0\u0247"+
    "\0\65\0\u027c\0\u02b1\0\u02e6\0\u02e6\0\65\0\u031b\0\u0350"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8"+
    "\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\65\0\65\0\u0636"+
    "\0\u066b\0\u0109\0\u06a0\0\u06d5\0\u070a\0\u073f\0\65\0\u0774"+
    "\0\65\0\65\0\u07a9\0\u07de\0\u0109\0\u0813\0\u0848\0\u087d"+
    "\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u0109\0\u09bb\0\u09f0"+
    "\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0601\0\u0b63"+
    "\0\u0b98\0\u0109\0\u0109\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0109"+
    "\0\u0109\0\u0ca1\0\u0109\0\u0cd6\0\u0d0b\0\u0109\0\u0d40\0\u0109"+
    "\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0e7e\0\u0b2e"+
    "\0\u0eb3\0\u0ee8\0\u0f1d\0\u0109\0\u0f52\0\u0774\0\u0f87\0\u0fbc"+
    "\0\u0ff1\0\u0109\0\u1026\0\u105b\0\u0109\0\u0109\0\u1090\0\u10c5"+
    "\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\u0109\0\u0109"+
    "\0\u1238\0\u0109\0\u0109\0\u126d\0\u12a2\0\u0109\0\u12d7\0\u0109"+
    "\0\u130c\0\u0109\0\u1341\0\u0109\0\u1376\0\u13ab\0\u0109\0\u0109";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\6\1\12\1\6\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\3\6\1\40\4\6\1\41\1\42\1\6\1\2\1\43"+
    "\1\2\1\44\1\45\1\46\1\2\1\46\1\47\67\0"+
    "\1\6\1\50\10\6\14\0\26\6\11\0\12\6\14\0"+
    "\4\6\1\51\21\6\11\0\1\6\1\52\10\6\14\0"+
    "\26\6\11\0\12\6\14\0\26\6\11\0\12\6\14\0"+
    "\7\6\1\53\16\6\11\0\2\6\1\54\7\6\14\0"+
    "\26\6\11\0\7\6\1\55\2\6\14\0\26\6\11\0"+
    "\7\6\1\56\2\6\14\0\26\6\26\0\1\57\74\0"+
    "\1\60\54\0\1\61\64\0\1\62\122\0\1\43\11\0"+
    "\2\6\1\63\7\6\14\0\1\6\1\64\24\6\11\0"+
    "\12\6\14\0\6\6\1\65\17\6\11\0\4\6\1\66"+
    "\5\6\14\0\26\6\11\0\2\6\1\67\7\6\14\0"+
    "\26\6\11\0\12\6\14\0\7\6\1\70\10\6\1\71"+
    "\5\6\11\0\12\6\14\0\7\6\1\72\16\6\11\0"+
    "\2\6\1\73\7\6\14\0\5\6\1\74\20\6\11\0"+
    "\2\6\1\75\7\6\14\0\26\6\11\0\2\6\1\76"+
    "\7\6\14\0\17\6\1\77\6\6\11\0\12\6\14\0"+
    "\12\6\1\100\13\6\11\0\12\6\14\0\17\6\1\101"+
    "\6\6\11\0\12\6\14\0\4\6\1\102\21\6\23\0"+
    "\1\103\17\0\1\104\5\0\1\104\12\0\1\43\10\0"+
    "\56\105\1\106\6\105\60\107\1\0\1\47\3\107\1\0"+
    "\2\6\1\110\7\6\14\0\26\6\11\0\1\111\11\6"+
    "\14\0\26\6\11\0\12\6\14\0\1\112\25\6\11\0"+
    "\12\6\14\0\1\113\25\6\11\0\10\6\1\114\1\6"+
    "\14\0\26\6\11\0\11\6\1\115\14\0\26\6\10\0"+
    "\26\60\1\116\36\60\1\0\12\6\14\0\21\6\1\117"+
    "\4\6\11\0\12\6\14\0\2\6\1\120\23\6\11\0"+
    "\1\6\1\121\10\6\14\0\26\6\11\0\12\6\14\0"+
    "\7\6\1\122\16\6\11\0\12\6\14\0\1\123\25\6"+
    "\11\0\12\6\14\0\11\6\1\124\14\6\11\0\12\6"+
    "\14\0\10\6\1\125\15\6\11\0\1\6\1\126\10\6"+
    "\14\0\26\6\11\0\12\6\14\0\7\6\1\127\16\6"+
    "\11\0\12\6\14\0\10\6\1\130\15\6\11\0\12\6"+
    "\14\0\4\6\1\131\21\6\11\0\12\6\14\0\15\6"+
    "\1\132\10\6\11\0\12\6\14\0\1\6\1\133\24\6"+
    "\11\0\3\6\1\134\6\6\14\0\26\6\64\0\1\135"+
    "\34\0\2\136\26\0\1\137\10\0\56\105\1\140\6\105"+
    "\56\0\1\105\7\0\3\6\1\141\6\6\14\0\3\6"+
    "\1\142\22\6\11\0\12\6\14\0\4\6\1\143\21\6"+
    "\11\0\11\6\1\144\14\0\26\6\11\0\12\6\14\0"+
    "\12\6\1\145\13\6\10\0\21\60\1\146\4\60\1\147"+
    "\32\60\1\0\3\60\1\0\12\6\14\0\7\6\1\150"+
    "\16\6\11\0\12\6\14\0\11\6\1\151\14\6\11\0"+
    "\12\6\14\0\4\6\1\152\21\6\11\0\12\6\14\0"+
    "\1\6\1\153\24\6\11\0\12\6\14\0\3\6\1\154"+
    "\22\6\11\0\12\6\14\0\7\6\1\155\16\6\11\0"+
    "\12\6\14\0\16\6\1\156\7\6\11\0\12\6\14\0"+
    "\20\6\1\157\5\6\11\0\12\6\14\0\1\6\1\160"+
    "\24\6\64\0\1\137\1\161\63\0\1\137\11\0\1\6"+
    "\1\162\10\6\14\0\26\6\11\0\12\6\14\0\4\6"+
    "\1\163\21\6\11\0\4\6\1\164\5\6\14\0\26\6"+
    "\11\0\12\6\14\0\13\6\1\165\12\6\10\0\21\60"+
    "\1\146\4\60\1\116\36\60\1\0\12\6\14\0\10\6"+
    "\1\166\15\6\11\0\12\6\14\0\10\6\1\167\15\6"+
    "\11\0\12\6\14\0\20\6\1\170\5\6\11\0\12\6"+
    "\14\0\10\6\1\171\15\6\11\0\12\6\14\0\4\6"+
    "\1\172\21\6\11\0\12\6\14\0\7\6\1\173\16\6"+
    "\43\0\1\104\5\0\1\104\13\0\1\161\10\0\4\6"+
    "\1\174\5\6\14\0\26\6\11\0\12\6\14\0\1\175"+
    "\25\6\11\0\12\6\14\0\10\6\1\176\15\6\11\0"+
    "\12\6\14\0\12\6\1\177\13\6\11\0\2\6\1\200"+
    "\7\6\14\0\26\6\11\0\12\6\14\0\1\6\1\201"+
    "\24\6\11\0\5\6\1\202\4\6\14\0\26\6\11\0"+
    "\12\6\14\0\5\6\1\203\20\6\11\0\12\6\14\0"+
    "\14\6\1\204\11\6\11\0\2\6\1\205\7\6\14\0"+
    "\26\6\11\0\1\6\1\206\10\6\14\0\26\6\11\0"+
    "\12\6\14\0\7\6\1\207\16\6\11\0\12\6\14\0"+
    "\4\6\1\210\21\6\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5088];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\1\1\3\11\1\1\1\11"+
    "\4\1\1\11\17\1\2\11\7\1\1\11\1\0\2\11"+
    "\20\1\5\0\6\1\1\0\17\1\1\0\10\1\1\0"+
    "\11\1\1\0\27\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 190) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error léxico. Caracter erroneo: "+yytext() + ", linea " + yyline + " columna " + yycolumn);
            }
          case 48: break;
          case 2: 
            { return new Symbol (sym.identifier,yyline, yycolumn, yytext());
            }
          case 49: break;
          case 3: 
            { return new Symbol (sym.punto);
            }
          case 50: break;
          case 4: 
            { return new Symbol(sym.dosPuntos);
            }
          case 51: break;
          case 5: 
            { return new Symbol(sym.puntoComa);
            }
          case 52: break;
          case 6: 
            { return new Symbol(sym.igual);
            }
          case 53: break;
          case 7: 
            { return new Symbol(sym.coma);
            }
          case 54: break;
          case 8: 
            { return new Symbol(sym.abrirPar);
            }
          case 55: break;
          case 9: 
            { return new Symbol(sym.cerrarPar);
            }
          case 56: break;
          case 10: 
            { return new Symbol(sym.menor);
            }
          case 57: break;
          case 11: 
            { return new Symbol(sym.mayor);
            }
          case 58: break;
          case 12: 
            { return new Symbol(sym.mas_);
            }
          case 59: break;
          case 13: 
            { return new Symbol(sym.menos);
            }
          case 60: break;
          case 14: 
            { return new Symbol(sym.mul);
            }
          case 61: break;
          case 15: 
            { return new Symbol (sym.numeric_integer_const,yyline, yycolumn,yytext());
            }
          case 62: break;
          case 16: 
            { System.out.print("");
            }
          case 63: break;
          case 17: 
            { 
            }
          case 64: break;
          case 18: 
            { return new Symbol(sym.or_);
            }
          case 65: break;
          case 19: 
            { return new Symbol(sym.puntosIgual);
            }
          case 66: break;
          case 20: 
            { return new Symbol(sym.menorIgual);
            }
          case 67: break;
          case 21: 
            { return new Symbol(sym.mayorIgual);
            }
          case 68: break;
          case 22: 
            { return new Symbol(sym.do_);
            }
          case 69: break;
          case 23: 
            { return new Symbol(sym.if_);
            }
          case 70: break;
          case 24: 
            { return new Symbol(sym.to_);
            }
          case 71: break;
          case 25: 
            { return new Symbol(sym.and_);
            }
          case 72: break;
          case 26: 
            { return new Symbol(sym.mod_);
            }
          case 73: break;
          case 27: 
            { return new Symbol(sym.div_);
            }
          case 74: break;
          case 28: 
            { return new Symbol (sym.var_);
            }
          case 75: break;
          case 29: 
            { return new Symbol(sym.end_);
            }
          case 76: break;
          case 30: 
            { return new Symbol(sym.for_);
            }
          case 77: break;
          case 31: 
            { return new Symbol(sym.not_);
            }
          case 78: break;
          case 32: 
            { return new Symbol (sym.numeric_real_const,yyline, yycolumn, yytext());
            }
          case 79: break;
          case 33: 
            { return new Symbol (sym.string_const,yyline, yycolumn, yytext());
            }
          case 80: break;
          case 34: 
            { return new Symbol(sym.unit_);
            }
          case 81: break;
          case 35: 
            { return new Symbol(sym.else_);
            }
          case 82: break;
          case 36: 
            { return new Symbol(sym.then_);
            }
          case 83: break;
          case 37: 
            { return new Symbol(sym.real_);
            }
          case 84: break;
          case 38: 
            { return new Symbol(sym.const_);
            }
          case 85: break;
          case 39: 
            { return new Symbol(sym.until_);
            }
          case 86: break;
          case 40: 
            { return new Symbol(sym.while_);
            }
          case 87: break;
          case 41: 
            { return new Symbol(sym.begin_);
            }
          case 88: break;
          case 42: 
            { return new Symbol(sym.repeat_);
            }
          case 89: break;
          case 43: 
            { return new Symbol(sym.downto_);
            }
          case 90: break;
          case 44: 
            { return new Symbol(sym.program_);
            }
          case 91: break;
          case 45: 
            { return new Symbol(sym.int_);
            }
          case 92: break;
          case 46: 
            { return new Symbol(sym.function_);
            }
          case 93: break;
          case 47: 
            { return new Symbol(sym.procedure_);
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
