
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package traductorPascalC;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int var_ = 29;
  public static final int mul = 20;
  public static final int end_ = 10;
  public static final int numeric_real_const = 5;
  public static final int unit_ = 27;
  public static final int repeat_ = 37;
  public static final int dosPuntos = 14;
  public static final int program_ = 2;
  public static final int begin_ = 9;
  public static final int do_ = 36;
  public static final int coma = 23;
  public static final int igual = 11;
  public static final int mod_ = 22;
  public static final int identifier = 3;
  public static final int menorIgual = 45;
  public static final int to_ = 41;
  public static final int cerrarPar = 16;
  public static final int then_ = 33;
  public static final int div_ = 21;
  public static final int procedure_ = 12;
  public static final int else_ = 34;
  public static final int not_ = 42;
  public static final int and_ = 25;
  public static final int downto_ = 40;
  public static final int menos = 19;
  public static final int menor = 43;
  public static final int until_ = 38;
  public static final int EOF = 0;
  public static final int int_ = 30;
  public static final int mas = 18;
  public static final int mayorIgual = 46;
  public static final int error = 1;
  public static final int mayor = 44;
  public static final int if_ = 32;
  public static final int function_ = 13;
  public static final int while_ = 35;
  public static final int abrirPar = 15;
  public static final int punto = 8;
  public static final int puntoComa = 7;
  public static final int const_ = 28;
  public static final int puntosIgual = 24;
  public static final int real_ = 31;
  public static final int for_ = 39;
  public static final int numeric_integer_const = 4;
  public static final int string_const = 6;
  public static final int lambda = 17;
  public static final int or_ = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "program_",
  "identifier",
  "numeric_integer_const",
  "numeric_real_const",
  "string_const",
  "puntoComa",
  "punto",
  "begin_",
  "end_",
  "igual",
  "procedure_",
  "function_",
  "dosPuntos",
  "abrirPar",
  "cerrarPar",
  "lambda",
  "mas",
  "menos",
  "mul",
  "div_",
  "mod_",
  "coma",
  "puntosIgual",
  "and_",
  "or_",
  "unit_",
  "const_",
  "var_",
  "int_",
  "real_",
  "if_",
  "then_",
  "else_",
  "while_",
  "do_",
  "repeat_",
  "until_",
  "for_",
  "downto_",
  "to_",
  "not_",
  "menor",
  "mayor",
  "menorIgual",
  "mayorIgual"
  };
}

